<script setup lang="ts">
import type { ConfigResponse } from '~/composables/useApi'
import { getAppDomain } from '~/composables/useApi'
import type { MLXModelsResponse, AppType } from '~/types'

const props = defineProps<{
  open: boolean
}>()

const emit = defineEmits<{
  'update:open': [value: boolean]
  created: []
}>()

const toast = useToast()
const { data: configData } = await useApiFetch<ConfigResponse>('/system/config')
const { data: mlxData } = await useApiFetch<MLXModelsResponse>('/mlx/models')

const appType = ref<AppType>('container')

const form = ref({
  name: '',
  image: '',
  model: '',
  port: 8080,
  memory: 0,
  cpus: 0,
  enableSSL: false
})

const isMLXSupported = computed(() => mlxData.value?.supported ?? false)
const mlxModels = computed(() => mlxData.value?.models ?? [])

// Environment variables
const envVars = ref<Array<{ key: string; value: string }>>([])

// Custom volumes
const volumes = ref<Array<{ name: string; containerPath: string }>>([])

const isOpen = computed({
  get: () => props.open,
  set: (value) => emit('update:open', value)
})

// Auto-generate domain from app name using config
const autoDomain = computed(() => {
  if (!form.value.name) return ''
  const name = form.value.name.toLowerCase().replace(/[^a-z0-9-]/g, '-')
  if (configData.value?.domain) {
    return getAppDomain(name, configData.value.domain)
  }
  return `${name}.pod`
})

// Domain suffix for placeholder display
const domainPlaceholder = computed(() => {
  if (configData.value?.domain?.base) {
    return `app-name.${configData.value.domain.base}`
  }
  return `app-name${configData.value?.domain?.suffix || '.pod'}`
})

function addEnvVar() {
  envVars.value.push({ key: '', value: '' })
  nextTick(() => {
    const inputs = document.querySelectorAll('#create-app-modal input[placeholder="KEY"]')
    const lastInput = inputs[inputs.length - 1] as HTMLInputElement
    lastInput?.focus()
  })
}

function removeEnvVar(index: number) {
  envVars.value.splice(index, 1)
}

function addVolume() {
  volumes.value.push({ name: '', containerPath: '' })
  nextTick(() => {
    const inputs = document.querySelectorAll('#create-app-modal input[placeholder="data"]')
    const lastInput = inputs[inputs.length - 1] as HTMLInputElement
    lastInput?.focus()
  })
}

function removeVolume(index: number) {
  volumes.value.splice(index, 1)
}

async function submit() {
  // Build env object from array
  const envObject: Record<string, string> = {}
  for (const { key, value } of envVars.value) {
    if (key.trim()) {
      envObject[key.trim()] = value
    }
  }

  // Build volumes array (host path will be auto-generated by backend)
  const volumesArray = volumes.value
    .filter(v => v.name.trim() && v.containerPath.trim())
    .map(v => ({
      name: v.name.trim(),
      container_path: v.containerPath.trim()
    }))

  try {
    const body: Record<string, unknown> = {
      name: form.value.name,
      type: appType.value,
      enable_ssl: form.value.enableSSL
    }

    if (appType.value === 'mlx') {
      // MLX app - only need model
      body.model = form.value.model
    } else {
      // Container app
      body.image = form.value.image || undefined
      body.port = form.value.port
      body.memory = form.value.memory || undefined
      body.cpus = form.value.cpus || undefined
      body.env = Object.keys(envObject).length > 0 ? envObject : undefined
      body.volumes = volumesArray.length > 0 ? volumesArray : undefined
    }

    await $api('/apps', {
      method: 'POST',
      body
    })
    isOpen.value = false
    // Reset form
    form.value = { name: '', image: '', model: '', port: 8080, memory: 0, cpus: 0, enableSSL: false }
    appType.value = 'container'
    envVars.value = []
    volumes.value = []
    toast.add({ title: 'App created successfully', color: 'success' })
    emit('created')
  } catch (error) {
    const message = error && typeof error === 'object' && 'data' in error
      ? (error as { data?: { error?: string } }).data?.error
      : 'An unexpected error occurred'
    toast.add({ title: 'Failed to create app', description: message, color: 'error' })
  }
}
</script>

<template>
  <UModal v-model:open="isOpen" title="Create New App">
    <template #body>
      <div id="create-app-modal" class="space-y-4">
        <!-- App Type Selection -->
        <UFormField label="App Type" required>
          <div class="flex gap-2">
            <UButton
              :variant="appType === 'container' ? 'solid' : 'outline'"
              @click="appType = 'container'"
              class="flex-1"
            >
              <UIcon name="i-heroicons-cube" class="w-4 h-4 mr-2" />
              Container
            </UButton>
            <UButton
              :variant="appType === 'mlx' ? 'solid' : 'outline'"
              :disabled="!isMLXSupported"
              @click="appType = 'mlx'"
              class="flex-1"
            >
              <UIcon name="i-heroicons-cpu-chip" class="w-4 h-4 mr-2" />
              LLM (MLX)
            </UButton>
          </div>
          <p v-if="!isMLXSupported" class="text-xs text-amber-600 mt-1">
            MLX requires macOS with Apple Silicon
          </p>
        </UFormField>

        <!-- Basic Info -->
        <UFormField label="App Name" required>
          <UInput v-model="form.name" placeholder="my-app" />
        </UFormField>

        <UFormField label="Domain">
          <div class="flex items-center gap-2 px-3 py-2 bg-gray-100 dark:bg-gray-800 rounded-md font-mono text-sm">
            <span class="text-gray-500">https://</span>
            <span>{{ autoDomain || domainPlaceholder }}</span>
          </div>
          <p class="text-xs text-gray-500 mt-1">Auto-assigned based on app name</p>
        </UFormField>

        <!-- MLX Model Selection -->
        <template v-if="appType === 'mlx'">
          <UFormField label="LLM Model" required>
            <USelectMenu
              v-model="form.model"
              :items="mlxModels.map(m => ({ label: `${m.name} (${m.size})`, value: m.id, description: m.description }))"
              placeholder="Select a model..."
              value-key="value"
            >
              <template #item="{ item }">
                <div>
                  <div class="font-medium">{{ item.label }}</div>
                  <div class="text-xs text-gray-500">{{ item.description }}</div>
                </div>
              </template>
            </USelectMenu>
            <p class="text-xs text-gray-500 mt-1">
              Models are downloaded from mlx-community on HuggingFace
            </p>
          </UFormField>

          <div class="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg text-sm">
            <div class="flex items-start gap-2">
              <UIcon name="i-heroicons-information-circle" class="w-5 h-5 text-blue-500 mt-0.5" />
              <div>
                <p class="font-medium text-blue-700 dark:text-blue-300">OpenAI-Compatible API</p>
                <p class="text-blue-600 dark:text-blue-400 mt-1">
                  Your LLM will expose an OpenAI-compatible API at your app domain.
                  Use it with any OpenAI SDK by pointing to your domain.
                </p>
              </div>
            </div>
          </div>
        </template>

        <!-- Container-specific fields -->
        <template v-else>
          <UFormField label="Docker Image" hint="Optional - can deploy later">
            <UInput v-model="form.image" placeholder="nginx:latest" />
          </UFormField>

          <UFormField label="Container Port">
            <UInput v-model.number="form.port" type="number" placeholder="8080" />
          </UFormField>

        <!-- Resource Limits -->
        <div class="grid grid-cols-2 gap-4">
          <UFormField label="Memory Limit (MB)" hint="0 = unlimited">
            <UInput v-model.number="form.memory" type="number" placeholder="512" />
          </UFormField>

          <UFormField label="CPU Limit" hint="0 = unlimited">
            <UInput v-model.number="form.cpus" type="number" step="0.1" placeholder="1.0" />
          </UFormField>
        </div>

        <!-- Environment Variables -->
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <label class="text-sm font-medium">Environment Variables</label>
            <UButton variant="ghost" size="xs" @click="addEnvVar">
              <UIcon name="i-heroicons-plus" class="w-4 h-4 mr-1" />
              Add
            </UButton>
          </div>

          <div v-if="envVars.length === 0" class="text-sm text-gray-500 py-2">
            No environment variables configured
          </div>

          <div v-for="(envVar, index) in envVars" :key="index" class="flex items-center gap-2">
            <input
              v-model="envVar.key"
              type="text"
              placeholder="KEY"
              class="flex-1 px-3 py-1.5 font-mono text-sm bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500"
            >
            <span class="text-gray-400">=</span>
            <input
              v-model="envVar.value"
              type="text"
              placeholder="value"
              class="flex-[2] px-3 py-1.5 font-mono text-sm bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500"
            >
            <UButton
              icon="i-heroicons-x-mark"
              color="error"
              variant="ghost"
              size="xs"
              @click="removeEnvVar(index)"
            />
          </div>
        </div>

        <!-- Persistent Volumes -->
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <label class="text-sm font-medium">Persistent Volumes</label>
            <UButton variant="ghost" size="xs" @click="addVolume">
              <UIcon name="i-heroicons-plus" class="w-4 h-4 mr-1" />
              Add
            </UButton>
          </div>

          <div v-if="volumes.length === 0" class="text-sm text-gray-500 py-2">
            No volumes configured - data will not persist
          </div>

          <div v-for="(vol, index) in volumes" :key="index" class="flex items-center gap-2">
            <input
              v-model="vol.name"
              type="text"
              placeholder="data"
              class="w-24 px-3 py-1.5 font-mono text-sm bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500"
            >
            <UIcon name="i-heroicons-arrow-right" class="w-4 h-4 text-gray-400" />
            <input
              v-model="vol.containerPath"
              type="text"
              placeholder="/var/lib/data"
              class="flex-1 px-3 py-1.5 font-mono text-sm bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500"
            >
            <UButton
              icon="i-heroicons-x-mark"
              color="error"
              variant="ghost"
              size="xs"
              @click="removeVolume(index)"
            />
          </div>

          <p v-if="volumes.length > 0" class="text-xs text-gray-500">
            Name: volume identifier | Path: mount point inside container
          </p>
        </div>
        </template>
      </div>
    </template>

    <template #footer>
      <div class="flex justify-end gap-2">
        <UButton variant="ghost" @click="isOpen = false">Cancel</UButton>
        <UButton :disabled="!form.name || (appType === 'mlx' && !form.model)" @click="submit">Create</UButton>
      </div>
    </template>
  </UModal>
</template>
